FROM node:18-alpine as build
WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install

FROM node:18-alpine AS runtime 
WORKDIR /app
COPY --from=build /app .
COPY index.js /app/
EXPOSE 4000