name: Application Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
      
      

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm run build

      - name: Build app container
        run: docker build -t pedrofsvalladares/infnet-guia-prod .
